#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
if [[ -s "${ZDOTDIR:-$HOME}/.zshrc_local" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshrc_local"
fi

# Maybe put this in ~/.zshrc_local
autoload -Uz compinit
zstyle ':completion:*' menu select
fpath+=~/.zfunc
compinit
